### ISSUE TITLE
Output Aardvark metadata lists version as 1.0

### ISSUE THREAD

**Issue by srappel** [OpenGeoMetadata/gbl-1_to_aardvark#3]
Output Aardvark metadata lists version as 1.0:

```
"gbl_mdVersion_s": "1.0"
```

The expected result would be:

```
"gbl_mdVersion_s": "Aardvark"
```

crosswalk csv lists:

`geoblacklight_version,gbl_mdVersion_s`

I assume we should just force set gbl_mdVersion_s to `Aardvark` instead of crosswalk

**Comment by karenmajewicz** [comment]
Yeah, that's an error. We should remove that from the crosswalk.
